#!/usr/bin/env python3
"""Sudoku puzzle generator for sudoku-gb.

Generates LEVEL_COUNT valid puzzles (unique solution, verified with a
counting solver capped at 2) and writes them as a generated C file
(src/puzzles_gen.c) ready to compile with GBDK-2020.

Usage:
    python3 tools/gen_puzzles.py [--seed N]

The generated file must NOT be edited by hand: to change the puzzles,
just re-run this script.
"""

import random
import sys

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

# (difficulty_name, puzzle_count, givens_target)
DIFFICULTIES = [
    ("EASY", 4, 42),
    ("MEDIUM", 4, 34),
    ("HARD", 4, 29),
]

SECRET_SEED_DEFAULT = 20260916


# ---------------------------------------------------------------------------
# Counting solver (cap at 2: enough to prove uniqueness)
# ---------------------------------------------------------------------------

def find_empty(board):
    """Return the index of the first empty cell (0), or -1 if full."""
    for i in range(81):
        if board[i] == 0:
            return i
    return -1


def candidates(board, idx):
    """Return the list of legal values (1-9) for cell idx."""
    row, col = divmod(idx, 9)
    used = set()
    for c in range(9):
        used.add(board[row * 9 + c])
    for r in range(9):
        used.add(board[r * 9 + col])
    br, bc = (row // 3) * 3, (col // 3) * 3
    for r in range(br, br + 3):
        for c in range(bc, bc + 3):
            used.add(board[r * 9 + c])
    return [v for v in range(1, 10) if v not in used]


def count_solutions(board, limit=2):
    """Count solutions (up to `limit`) with backtracking + MRV."""
    # MRV: pick the empty cell with fewest candidates (effective pruning).
    best, best_cands = -1, None
    for i in range(81):
        if board[i] == 0:
            cands = candidates(board, i)
            if not cands:
                return 0
            if best_cands is None or len(cands) < len(best_cands):
                best, best_cands = i, cands
                if len(best_cands) == 1:
                    break
    if best == -1:
        return 1  # full board: one solution found
    total = 0
    for v in best_cands:
        board[best] = v
        total += count_solutions(board, limit)
        board[best] = 0
        if total >= limit:
            break
    return total


def fill_full_grid(rng):
    """Generate a valid full grid with randomized backtracking."""
    board = [0] * 81

    def rec():
        idx = find_empty(board)
        if idx == -1:
            return True
        vals = candidates(board, idx)
        rng.shuffle(vals)
        for v in vals:
            board[idx] = v
            if rec():
                return True
            board[idx] = 0
        return False

    rec()
    return board


def dig_holes(solution, givens_target, rng):
    """Dig cells while keeping a unique solution. Return the puzzle."""
    puzzle = solution[:]
    order = list(range(81))
    rng.shuffle(order)
    givens = 81
    for idx in order:
        if givens <= givens_target:
            break
        backup = puzzle[idx]
        puzzle[idx] = 0
        trial = puzzle[:]
        if count_solutions(trial, 2) != 1:
            puzzle[idx] = backup  # restore: needed for uniqueness
        else:
            givens -= 1
    return puzzle


def to_str(board):
    return "".join(str(v) for v in board)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    seed = SECRET_SEED_DEFAULT
    for arg in sys.argv[1:]:
        if arg.startswith("--seed"):
            seed = int(arg.split("=")[1])

    rng = random.Random(seed)
    levels = []  # (difficulty, givens_str)
    for diff_name, count, givens_target in DIFFICULTIES:
        for _ in range(count):
            solution = fill_full_grid(rng)
            puzzle = dig_holes(solution, givens_target, rng)
            # Final sanity check: unique solution, consistent with it.
            assert count_solutions(puzzle[:], 2) == 1, "puzzle without unique solution!"
            for i in range(81):
                assert puzzle[i] == 0 or puzzle[i] == solution[i]
            n_givens = sum(1 for v in puzzle if v != 0)
            print(f"{diff_name}: givens={n_givens} (target {givens_target})")
            levels.append((diff_name, to_str(puzzle)))

    with open("src/puzzles_gen.c", "w") as f:
        f.write("/* GENERATED by tools/gen_puzzles.py -- DO NOT edit by hand. */\n")
        f.write("/* Only givens are stored. The solution is NOT needed: every\n")
        f.write(" * puzzle has a unique solution, so 'full and valid' == win. */\n")
        f.write('#include "puzzles.h"\n\n')
        f.write("const Puzzle puzzles[LEVEL_COUNT] = {\n")
        for diff_name, givens in levels:
            f.write(f'    {{ DIFF_{diff_name}, "{givens}" }},\n')
        f.write("};\n")
    print(f"Wrote {len(levels)} puzzles to src/puzzles_gen.c")


if __name__ == "__main__":
    main()
